spring.application.name=LifeHubServer
server.port=9000
spring.profiles.active=dev

# SpringDoc OpenAPI (Swagger) \u914D\u7F6E
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.show-actuator=false
# \u626B\u63CF\u7684\u5305\u8DEF\u5F84
springdoc.packages-to-scan=com.xhn
# \u8DEF\u5F84\u5339\u914D\u89C4\u5219
springdoc.paths-to-match=/**

logging.config=classpath:logback-spring.xml
logging.level.com.xhn=info


spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false

# \u5173\u95EDSpringAI\u7684\u81EA\u52A8\u88C5\u914D
spring.ai.mcp.server.enabled=false
spring.ai.mcp.server.annotation-scanner.enabled=false
